# Coin Flips and Die Rolls
Use NumPy to create simulations and compute proportions for the following outcomes. The first one is done for you.

In [1]:
# import numpy
import numpy as np

### 1. Two fair coin flips produce exactly two heads

In [2]:
# simulate 1 million tests of two fair coin flips
tests = np.random.randint(2, size=(int(1e6), 2))

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly two heads
(test_sums == 0).mean()

0.250614

In [3]:
test_sums

array([1, 1, 2, ..., 0, 2, 1])

In [4]:
tests

array([[0, 1],
       [1, 0],
       [1, 1],
       ..., 
       [0, 0],
       [1, 1],
       [0, 1]])

### 2. Three fair coin flips produce exactly one head

In [5]:
# simulate 1 million tests of three fair coin flips
tests = np.random.randint(2, size=(int(1e6), 3))

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly one head
(test_sums == 2).mean()

0.37503399999999998

In [6]:
test_sums

array([2, 1, 2, ..., 2, 1, 2])

In [7]:
tests

array([[1, 0, 1],
       [1, 0, 0],
       [1, 0, 1],
       ..., 
       [0, 1, 1],
       [0, 0, 1],
       [0, 1, 1]])

### 3. Three biased coin flips with P(H) = 0.6 produce exactly one head

In [8]:
# simulate 1 million tests of three bias coin flips
# hint: use np.random.choice()
tests = np.random.choice([0, 1], size=(int(1e6), 3), p=[0.6, 0.4])

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly one head
(test_sums == 2).mean()

0.28873599999999999

In [9]:
test_sums

array([0, 0, 2, ..., 2, 0, 1])

In [10]:
tests

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 0],
       ..., 
       [1, 0, 1],
       [0, 0, 0],
       [1, 0, 0]])

### 4. A die rolls an even number

In [11]:
# simulate 1 million tests of one die roll
tests = np.random.choice([1, 2, 3, 4, 5, 6], size=(int(1e6)))

# proportion of tests that produced an even number
proportion_even = sum(tests % 2 == 0) / len(tests)

In [12]:
proportion_even

0.50037500000000001

In [13]:
tests

array([1, 6, 4, ..., 3, 1, 2])

### 5. Two dice roll a double

In [14]:
# simulate the first million die rolls
first = np.random.choice([1, 2, 3, 4, 5, 6], size=(int(1e6)))

# simulate the second million die rolls
second = np.random.choice([1, 2, 3, 4, 5, 6], size=(int(1e6)))

# proportion of tests where the 1st and 2nd die rolled the same number
proportion_double = sum(first == second) / len(first)

In [15]:
proportion_double

0.166378